/**
 * Maps Polymarket tagId -> display type name for grouping.
 * Tag list comes from real Polymarket Gamma API; this file only defines how to group them.
 */

/** tagId (lowercase) -> type name for sidebar grouping */
export const TAG_ID_TO_TYPE: Record<string, string> = {
  epl: "Soccer / Association football",
  lal: "Soccer / Association football",
  acn: "Soccer / Association football",
  fl1: "Soccer / Association football",
  bun: "Soccer / Association football",
  sea: "Soccer / Association football",
  ucl: "Soccer / Association football",
  uel: "Soccer / Association football",
  afc: "Soccer / Association football",
  ofc: "Soccer / Association football",
  fif: "Soccer / Association football",
  ere: "Soccer / Association football",
  arg: "Soccer / Association football",
  itc: "Soccer / Association football",
  mex: "Soccer / Association football",
  lib: "Soccer / Association football",
  sud: "Soccer / Association football",
  tur: "Soccer / Association football",
  con: "Soccer / Association football",
  cof: "Soccer / Association football",
  uef: "Soccer / Association football",
  caf: "Soccer / Association football",
  rus: "Soccer / Association football",
  efa: "Soccer / Association football",
  efl: "Soccer / Association football",
  cdr: "Soccer / Association football",
  dfb: "Soccer / Association football",
  bra: "Soccer / Association football",
  jap: "Soccer / Association football",
  ja2: "Soccer / Association football",
  kor: "Soccer / Association football",
  spl: "Soccer / Association football",
  chi: "Soccer / Association football",
  aus: "Soccer / Association football",
  ind: "Soccer / Association football",
  nor: "Soccer / Association football",
  den: "Soccer / Association football",
  por: "Soccer / Association football",
  col: "Soccer / Association football",
  cde: "Soccer / Association football",
  mls: "Soccer / Association football",
  mar1: "Soccer / Association football",
  egy1: "Soccer / Association football",
  cze1: "Soccer / Association football",
  bol1: "Soccer / Association football",
  rou1: "Soccer / Association football",
  mwoh: "Soccer / Association football",
  bra2: "Soccer / Association football",
  per1: "Soccer / Association football",
  wwoh: "Soccer / Association football",
  col1: "Soccer / Association football",
  ukr1: "Soccer / Association football",
  chi1: "Soccer / Association football",
  uwcl: "Soccer / Association football",
  "j2-100": "Soccer / Association football",
  "j1-100": "Soccer / Association football",
  nba: "Basketball",
  ncaab: "Basketball",
  wnba: "Basketball",
  cbb: "Basketball",
  cwbb: "Basketball",
  bkligend: "Basketball",
  bknbl: "Basketball",
  bkseriea: "Basketball",
  bkcba: "Basketball",
  bkfr1: "Basketball",
  bkarg: "Basketball",
  bkkbl: "Basketball",
  euroleague: "Basketball",
  wll: "Basketball",
  bkcl: "Basketball",
  odi: "Cricket",
  t20: "Cricket",
  test: "Cricket",
  crban: "Cricket",
  crint: "Cricket",
  craus: "Cricket",
  creng: "Cricket",
  crnew: "Cricket",
  crind: "Cricket",
  crsou: "Cricket",
  crpak: "Cricket",
  cruae: "Cricket",
  cru19wc: "Cricket",
  crwpl20: "Cricket",
  crwncl: "Cricket",
  crwt20wcgq: "Cricket",
  crafgwi20: "Cricket",
  crbtnmlyhkg20: "Cricket",
  cricipl: "Cricket",
  cricpsl: "Cricket",
  criccpl: "Cricket",
  cricsm: "Cricket",
  cricsa20: "Cricket",
  crict20plw: "Cricket",
  criccsat20w: "Cricket",
  cricwncl: "Cricket",
  cricss: "Cricket",
  crichkt20w: "Cricket",
  criclcl: "Cricket",
  cricbbl: "Cricket",
  crict20blast: "Cricket",
  cricbpl: "Cricket",
  crict20lpl: "Cricket",
  cricilt20: "Cricket",
  cricmlc: "Cricket",
  cricpakt20cup: "Cricket",
  cricnt20c: "Cricket",
  cricthunderbolt: "Cricket",
  cricps: "Cricket",
  ipl: "Cricket",
  dota2: "Esports / Gaming",
  lol: "Esports / Gaming",
  lcs: "Esports / Gaming",
  val: "Esports / Gaming",
  cs2: "Esports / Gaming",
  mlbb: "Esports / Gaming",
  ow: "Esports / Gaming",
  codmw: "Esports / Gaming",
  fifa: "Esports / Gaming",
  rutopft: "Esports / Gaming",
  pubg: "Esports / Gaming",
  r6siege: "Esports / Gaming",
  rl: "Esports / Gaming",
  lpl: "Esports / Gaming",
  psp: "Esports / Gaming",
  wildrift: "Esports / Gaming",
  sc2: "Esports / Gaming",
  sc: "Esports / Gaming",
  nfl: "American football",
  cfb: "American football",
  mlb: "Baseball",
  kbo: "Baseball",
  wbc: "Baseball",
  nhl: "Hockey",
  shl: "Hockey",
  cehl: "Hockey",
  dehl: "Hockey",
  snhl: "Hockey",
  khl: "Hockey",
  ahl: "Hockey",
  atp: "Tennis",
  wta: "Tennis",
  wttmen: "Tennis",
  ufc: "MMA / Combat",
  zuffa: "MMA / Combat",
  pll: "Other",
  abb: "Other",
  csa: "Other",
  sasa: "Other",
  she: "Other",
  hok: "Other",
  ruprem: "Other",
  ssc: "Other",
  rusixnat: "Other",
  rueuchamp: "Other",
  ruurc: "Other",
  rusrp: "Other",
  ruchamp: "Other",
};

/** Order of group names in the tree (Other last). */
export const ORDERED_TYPE_NAMES: string[] = [
  "Soccer / Association football",
  "Basketball",
  "Cricket",
  "Esports / Gaming",
  "American football",
  "Baseball",
  "Hockey",
  "Tennis",
  "MMA / Combat",
  "Other",
];

/** Tag IDs that belong to each type (for live slugs by sport). */
export function getTagIdsByType(): Map<string, string[]> {
  const byType = new Map<string, string[]>();
  for (const [tagId, typeName] of Object.entries(TAG_ID_TO_TYPE)) {
    if (!byType.has(typeName)) byType.set(typeName, []);
    byType.get(typeName)!.push(tagId);
  }
  return byType;
}
